/* Signature Pianos — inventory data
   Shared by instruments.html (catalogue grid) and piano.html (product page).
   Add/edit entries here; the pages re-render automatically. */

const PIANOS = [

  /* ============ GRAND PIANOS ============ */
  {
    id: 'yamaha-c3',
    name: 'Yamaha C3',
    brand: 'Yamaha',
    model: 'C3',
    category: 'grand',
    categoryLabel: 'Grand Piano',
    condition: 'pre-loved',
    year: 2012,
    price: 18500,
    priceLabel: 'From $18,500',
    summary: 'A 6\'1" concert-quality grand. Yamaha\'s most popular C-series for serious students and small recital spaces.',
    description: 'The C3 is a workhorse of professional pianos worldwide. At 6 feet 1 inch, it offers the full tonal palette of a longer concert grand in a footprint that fits a Melbourne home, school, or recital space. Premium spruce soundboard, V-pro cast iron frame, and the same hammer construction used in Yamaha\'s flagship CFX. This 2012 example is in excellent condition with original polished ebony finish and full service history.',
    specs: {
      length: '6\' 1" (185 cm)',
      width: '60.6" (154 cm)',
      finish: 'Polished Ebony',
      keys: '88 weighted',
      pedals: '3 (with sostenuto)',
      country: 'Japan',
    },
  },
  {
    id: 'kawai-gl-30',
    name: 'Kawai GL-30',
    brand: 'Kawai',
    model: 'GL-30',
    category: 'grand',
    categoryLabel: 'Baby Grand',
    condition: 'new',
    year: 2024,
    price: 24800,
    priceLabel: 'From $24,800',
    summary: 'Kawai\'s 5\'5" baby grand — refined Millennium III action, perfect for medium living rooms.',
    description: 'The GL-30 brings Kawai\'s renowned Millennium III action into a 166cm baby grand that suits Melbourne apartments and townhouses. Built in Japan with the same craftsmanship as Kawai\'s larger concert instruments. The carbon-fibre composite action parts deliver remarkable repetition speed and tonal control. Sealed soundboard handles Melbourne\'s humidity swings without losing voice.',
    specs: {
      length: '5\' 5" (166 cm)',
      width: '59" (150 cm)',
      finish: 'Polished Ebony',
      keys: '88 weighted',
      pedals: '3 (with sostenuto)',
      country: 'Japan',
    },
  },
  {
    id: 'shigeru-kawai-sk-2',
    name: 'Shigeru Kawai SK-2',
    brand: 'Shigeru Kawai',
    model: 'SK-2',
    category: 'grand',
    categoryLabel: 'Concert Grand',
    condition: 'new',
    year: 2024,
    price: 69900,
    priceLabel: 'From $69,900',
    summary: 'Hand-finished in Ryuyo. Concert-hall voicing in a 5\'11" frame — the piano you keep for life.',
    description: 'Shigeru Kawai pianos are individually crafted by Master Piano Artisans in Kawai\'s exclusive Shigeru Kawai Research and Development Facility in Ryuyo, Japan. Each instrument receives over 100 hours of voicing, regulation, and refinement before it leaves the workshop. The SK-2 at 5\'11" offers full concert tonal range with a touch most pianists describe as transformative. Truly the instrument you buy once.',
    specs: {
      length: '5\' 11" (181 cm)',
      width: '60" (152 cm)',
      finish: 'Polished Ebony',
      keys: '88 weighted (ivorite tops)',
      pedals: '3 (with sostenuto)',
      country: 'Japan (Shigeru Kawai facility)',
    },
  },
  {
    id: 'yamaha-c7x',
    name: 'Yamaha C7X',
    brand: 'Yamaha',
    model: 'C7X',
    category: 'grand',
    categoryLabel: 'Semi-Concert Grand',
    condition: 'pre-loved',
    year: 2018,
    price: 42500,
    priceLabel: 'From $42,500',
    summary: 'A 7\'6" semi-concert grand built for recording studios, large halls, and serious performance.',
    description: 'The C7X is Yamaha\'s preferred instrument for many Australian conservatoriums and recording studios. At 7\'6", it produces a richer, more enveloping tone than the C-series shorter grands, with longer string speaking length giving extraordinary bass clarity. This pre-loved 2018 example was a private acquisition from a Melbourne recording studio; bench, dehumidifier, and complete maintenance log included.',
    specs: {
      length: '7\' 6" (227 cm)',
      width: '61" (155 cm)',
      finish: 'Polished Ebony',
      keys: '88 weighted',
      pedals: '3 (with sostenuto)',
      country: 'Japan',
    },
  },

  /* ============ UPRIGHT PIANOS ============ */
  {
    id: 'yamaha-u1',
    name: 'Yamaha U1',
    brand: 'Yamaha',
    model: 'U1',
    category: 'upright',
    categoryLabel: 'Studio Upright',
    condition: 'pre-loved',
    year: 2015,
    price: 11500,
    priceLabel: 'From $11,500',
    summary: 'The studio upright generations of pianists have trained on. 121cm height, professional action.',
    description: 'The U1 is the most-bought professional upright in the world. At 121cm, it delivers tone and touch comparable to entry-level grands while taking only a fraction of the floor space. Every Yamaha U1 we sell is fully serviced, re-regulated, and re-voiced by our in-house technician before delivery. This 2015 example shows minimal wear.',
    specs: {
      height: '4\' 0" (121 cm)',
      width: '60" (153 cm)',
      finish: 'Polished Ebony',
      keys: '88 weighted',
      pedals: '3 (with practice mute)',
      country: 'Japan',
    },
  },
  {
    id: 'kawai-k-300',
    name: 'Kawai K-300',
    brand: 'Kawai',
    model: 'K-300',
    category: 'upright',
    categoryLabel: 'Professional Upright',
    condition: 'new',
    year: 2024,
    price: 9400,
    priceLabel: 'From $9,400',
    summary: 'Concert tone in a contemporary upright. A buy-once instrument for serious home practice.',
    description: 'The K-300 is Kawai\'s most popular professional upright. Mahogany hammers, solid spruce soundboard, and the Millennium III action with carbon-fibre components — the same action geometry as Kawai\'s grands. New, with Kawai\'s full 10-year warranty.',
    specs: {
      height: '4\' 2" (122 cm)',
      width: '58.5" (149 cm)',
      finish: 'Polished Ebony',
      keys: '88 weighted',
      pedals: '3 (with practice mute)',
      country: 'Japan',
    },
  },
  {
    id: 'yamaha-b2',
    name: 'Yamaha b2',
    brand: 'Yamaha',
    model: 'b2',
    category: 'upright',
    categoryLabel: 'Upright',
    condition: 'new',
    year: 2024,
    price: 7800,
    priceLabel: 'From $7,800',
    summary: 'Acoustic warmth in a compact upright. Melbourne homes love this one for its honest tone.',
    description: 'The b2 is built in Indonesia at Yamaha\'s dedicated PIM facility to the same standards as their Japanese-built siblings. At 113cm it fits anywhere — but the tone and touch are unmistakably Yamaha. The most-recommended first acoustic for families starting lessons.',
    specs: {
      height: '3\' 8" (113 cm)',
      width: '58" (148 cm)',
      finish: 'Polished Ebony',
      keys: '88 weighted',
      pedals: '3 (with practice mute)',
      country: 'Indonesia',
    },
  },
  {
    id: 'kawai-k-500',
    name: 'Kawai K-500',
    brand: 'Kawai',
    model: 'K-500',
    category: 'upright',
    categoryLabel: 'Professional Upright',
    condition: 'new',
    year: 2024,
    price: 12200,
    priceLabel: 'From $12,200',
    summary: 'Built for serious practice — refined action, rich sustain, near-grand response.',
    description: 'The K-500 is Kawai\'s 130cm professional upright. The taller cabinet allows for longer bass strings and a larger soundboard, producing tonal richness closer to a baby grand than most uprights. NEOTEX key surfaces, Kawai\'s signature feel.',
    specs: {
      height: '4\' 3" (130 cm)',
      width: '58.5" (149 cm)',
      finish: 'Polished Ebony',
      keys: '88 weighted (NEOTEX surface)',
      pedals: '3 (with practice mute)',
      country: 'Japan',
    },
  },

  /* ============ DIGITAL PIANOS ============ */
  {
    id: 'roland-fp-30x',
    name: 'Roland FP-30X',
    brand: 'Roland',
    model: 'FP-30X',
    category: 'digital',
    categoryLabel: 'Portable Digital',
    condition: 'new',
    year: 2024,
    price: 1399,
    priceLabel: 'From $1,399',
    summary: 'A trusted first piano — weighted keys, honest tone, room to grow.',
    description: 'Roland\'s FP-30X is the most-recommended portable digital piano under $2,000. PHA-4 Standard keyboard with escapement and ivory feel, SuperNATURAL tone generator, and Bluetooth MIDI for apps. The kind of digital that doesn\'t feel like a compromise.',
    specs: {
      keys: '88 weighted (PHA-4 Standard)',
      polyphony: '256 notes',
      sounds: '56 tones, 30 rhythms',
      connectivity: 'Bluetooth MIDI, USB',
      weight: '14.8 kg',
    },
  },
  {
    id: 'kawai-kdp120',
    name: 'Kawai KDP120',
    brand: 'Kawai',
    model: 'KDP120',
    category: 'digital',
    categoryLabel: 'Console Digital',
    condition: 'new',
    year: 2024,
    price: 2299,
    priceLabel: 'From $2,299',
    summary: 'A console digital that feels like a real piano without the maintenance.',
    description: 'The KDP120 brings Kawai\'s Responsive Hammer Compact II action and Harmonic Imaging sound into a beautiful console cabinet. Bluetooth MIDI + Audio for streaming backing tracks. Triple pedal system, integrated bench. The closest a digital comes to an acoustic feel at this price.',
    specs: {
      keys: '88 weighted (RHC II)',
      polyphony: '192 notes',
      sounds: '15 tones',
      connectivity: 'Bluetooth MIDI + Audio, USB',
      pedals: '3 (integrated)',
    },
  },
  {
    id: 'yamaha-p-145',
    name: 'Yamaha P-145',
    brand: 'Yamaha',
    model: 'P-145',
    category: 'digital',
    categoryLabel: 'Portable Digital',
    condition: 'new',
    year: 2024,
    price: 1199,
    priceLabel: 'From $1,199',
    summary: 'Yamaha tone, beginner-friendly, ideal for the family living room.',
    description: 'The P-145 replaces the beloved P-45 in Yamaha\'s entry-level portable range. GHC (Graded Hammer Compact) keyboard, voiced from Yamaha\'s CFX concert grand. Slim, lightweight, and the simplest "just play" setup we sell.',
    specs: {
      keys: '88 weighted (GHC)',
      polyphony: '64 notes',
      sounds: '10 tones',
      connectivity: 'USB, headphone out',
      weight: '11.5 kg',
    },
  },
  {
    id: 'casio-px-s1100',
    name: 'Casio Privia PX-S1100',
    brand: 'Casio',
    model: 'PX-S1100',
    category: 'digital',
    categoryLabel: 'Slim Portable Digital',
    condition: 'new',
    year: 2024,
    price: 1099,
    priceLabel: 'From $1,099',
    summary: 'A slim digital that fits anywhere and feels right under beginner hands.',
    description: 'At just 23cm deep, the PX-S1100 is the slimmest weighted-action digital on the market. Smart Hammer Action Keyboard with simulated ebony/ivory key surfaces, Bluetooth Audio for streaming through the speakers. Battery option for travel or buskers.',
    specs: {
      keys: '88 weighted (Smart Hammer)',
      polyphony: '192 notes',
      sounds: '18 tones',
      connectivity: 'Bluetooth Audio, USB',
      weight: '11.2 kg',
    },
  },

];

/* Lookup helpers used by both pages */
function getPianoById(id) {
  return PIANOS.find(p => p.id === id);
}
function getCategoryPianos(category) {
  return PIANOS.filter(p => p.category === category);
}
function getBrands() {
  /* Display order — most-stocked / most-recognised first.
     Any new brand added to inventory that isn't in this list falls
     through to alphabetical at the end. */
  const priority = ['Yamaha', 'Kawai', 'Shigeru Kawai', 'Roland', 'Casio'];
  const all = Array.from(new Set(PIANOS.map(p => p.brand)));
  const ordered = [];
  priority.forEach(b => { if (all.includes(b)) ordered.push(b); });
  all.filter(b => !priority.includes(b)).sort().forEach(b => ordered.push(b));
  return ordered;
}
